export const ERROR_CODES = {
  UNAUTHORIZED_REQUEST: 'unauthorized request',
  JWT_INVALID_SIGNATURE: 'jwt signature is invalid',
  FAILED_TO_GET_MOVIE: 'failed to get movie',
  FAILED_TO_ADD_MOVIE: 'failed to add movie',
  FAILED_TO_UPDATE_MOVIE: 'failed to update movie',
  FAILED_TO_DELETE_MOVIE: 'failed to delete movie',
  FAILED_TO_GET_USER: 'failed to get user',
  DUPLICATED_USER_FOUND: 'duplicated user found',
  FAILED_TO_FOUND_USER: 'failed to found user',
  FAILED_TO_GET_USER_DETAILS: 'failed to get user details',
  FAILED_TO_GET_USERS: 'failed to get users',
  FAILED_TO_ADD_USER: 'failed to add user',
  FAILED_TO_UPDATE_USER: 'failed to update user',
  FAILED_TO_DELETE_USER: 'failed to delete user',
  FAILED_TO_MATCH_CHECK_PASSWORD: 'failed to match check password',
} as const;
